-- MySQL Script generated by MySQL Workbench
-- Thu Oct 28 19:17:08 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Endereco` (
  `CEP` VARCHAR(10) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(25) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`CEP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `codigo` INT NOT NULL,
  `telefone` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`, `CEP`),
  INDEX `fk_Cliente_Endereco1_idx` (`CEP` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`CEP`)
    REFERENCES `mydb`.`Endereco` (`CEP`)
    ON DELETE NO ACTION
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `codigo` INT NOT NULL,
  `unidade` INT NOT NULL,
  `qtdEstoque` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `ultimaVenda` DATE NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`formaDePagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`formaDePagamento` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `codigo` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `formaDePagamento` INT NOT NULL,
  `precoTotal` DOUBLE NOT NULL,
  `codigoCliente` INT NULL,
  PRIMARY KEY (`codigo`, `formaDePagamento`),
  INDEX `fk_Venda_Cliente1_idx` (`codigoCliente` ASC) VISIBLE,
  INDEX `fk_Venda_formaDePagamento1_idx` (`formaDePagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`codigoCliente`)
    REFERENCES `mydb`.`Cliente` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_formaDePagamento1`
    FOREIGN KEY (`formaDePagamento`)
    REFERENCES `mydb`.`formaDePagamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`itemVenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`itemVenda` (
  `codigoVenda` INT NOT NULL,
  `codigoProduto` INT NOT NULL,
  `qtdVendida` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`codigoVenda`, `codigoProduto`),
  INDEX `fk_itemVenda_Produto1_idx` (`codigoProduto` ASC) VISIBLE,
  CONSTRAINT `fk_itemVenda_Venda`
    FOREIGN KEY (`codigoVenda`)
    REFERENCES `mydb`.`Venda` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemVenda_Produto1`
    FOREIGN KEY (`codigoProduto`)
    REFERENCES `mydb`.`Produto` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
