-- MySQL Script generated by MySQL Workbench
-- ter 02 nov 2021 12:05:23
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bdpdv
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bdpdv
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bdpdv` ;
USE `bdpdv` ;

-- -----------------------------------------------------
-- Table `bdpdv`.`endereco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdpdv`.`endereco` (
  `CEP` VARCHAR(10) NOT NULL,
  `rua` VARCHAR(100) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(25) NULL,
  `cidade` VARCHAR(45) NOT NULL,
  `UF` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`CEP`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdpdv`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdpdv`.`cliente` (
  `codigo` INT NOT NULL,
  `telefone` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `CEP` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`, `CEP`),
  INDEX `fk_Cliente_Endereco1_idx` (`CEP` ASC) VISIBLE,
  CONSTRAINT `fk_Cliente_Endereco1`
    FOREIGN KEY (`CEP`)
    REFERENCES `bdpdv`.`endereco` (`CEP`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdpdv`.`produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdpdv`.`produto` (
  `codigo` INT NOT NULL,
  `unidade` INT NOT NULL,
  `qtdEstoque` INT NOT NULL,
  `nome` VARCHAR(100) NOT NULL,
  `preco` DOUBLE NOT NULL,
  `ultimaVenda` DATE NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdpdv`.`formadepagamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdpdv`.`formadepagamento` (
  `codigo` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `valorTotal` DOUBLE NOT NULL,
  PRIMARY KEY (`codigo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdpdv`.`venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdpdv`.`venda` (
  `codigo` INT NOT NULL,
  `data` DATE NOT NULL,
  `hora` TIME NOT NULL,
  `formaDePagamento` INT NOT NULL,
  `precoTotal` DOUBLE NOT NULL,
  `codigoCliente` INT NULL,
  PRIMARY KEY (`codigo`, `formaDePagamento`),
  INDEX `fk_Venda_Cliente1_idx` (`codigoCliente` ASC) VISIBLE,
  INDEX `fk_Venda_formaDePagamento1_idx` (`formaDePagamento` ASC) VISIBLE,
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`codigoCliente`)
    REFERENCES `bdpdv`.`cliente` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Venda_formaDePagamento1`
    FOREIGN KEY (`formaDePagamento`)
    REFERENCES `bdpdv`.`formadepagamento` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bdpdv`.`itemvenda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bdpdv`.`itemvenda` (
  `codigoVenda` INT NOT NULL,
  `codigoProduto` INT NOT NULL,
  `qtdVendida` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  PRIMARY KEY (`codigoVenda`, `codigoProduto`),
  INDEX `fk_itemVenda_Produto1_idx` (`codigoProduto` ASC) VISIBLE,
  CONSTRAINT `fk_itemVenda_Venda`
    FOREIGN KEY (`codigoVenda`)
    REFERENCES `bdpdv`.`venda` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itemVenda_Produto1`
    FOREIGN KEY (`codigoProduto`)
    REFERENCES `bdpdv`.`produto` (`codigo`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
